[providers]
providers = ["php", "node"]

[phases.setup]
nixPkgs = ["...", "php82Extensions.intl", "php82Extensions.zip", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[phases.build]
cmds = [
    "npm install",
    "npm run build"
]